// Package store keeps recipes as folders on disk. It is the source of truth:
// the SQLite index is rebuilt from here and can always be deleted.
package store

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"cookbook/internal/recipe"
)

var (
	ErrNotFound = errors.New("recipe not found")
	ErrExists   = errors.New("recipe already exists")
)

// ConflictError is returned when a save carries a stale revision.
type ConflictError struct{ Current *recipe.Recipe }

func (e *ConflictError) Error() string {
	return fmt.Sprintf("recipe was changed elsewhere (now at rev %d)", e.Current.Rev)
}

const historyKeep = 20

type Store struct {
	Root string // <data>
	mu   sync.Mutex
}

func New(root string) (*Store, error) {
	for _, d := range []string{"recipes", "trash", "templates"} {
		if err := os.MkdirAll(filepath.Join(root, d), 0o755); err != nil {
			return nil, err
		}
	}
	return &Store{Root: root}, nil
}

func (s *Store) Dir(id string) string      { return filepath.Join(s.Root, "recipes", id) }
func (s *Store) MediaDir(id string) string { return filepath.Join(s.Dir(id), "media") }
func (s *Store) metaPath(id string) string { return filepath.Join(s.Dir(id), "meta.json") }
func (s *Store) PDFPath(id, lang string) string {
	return filepath.Join(s.Dir(id), "output-"+lang+".pdf")
}

// IDs lists every recipe folder that has a meta.json.
func (s *Store) IDs() ([]string, error) {
	entries, err := os.ReadDir(filepath.Join(s.Root, "recipes"))
	if err != nil {
		return nil, err
	}
	var ids []string
	for _, e := range entries {
		if !e.IsDir() || !recipe.ValidID(e.Name()) {
			continue
		}
		if _, err := os.Stat(s.metaPath(e.Name())); err == nil {
			ids = append(ids, e.Name())
		}
	}
	sort.Strings(ids)
	return ids, nil
}

func (s *Store) Load(id string) (*recipe.Recipe, error) {
	if !recipe.ValidID(id) {
		return nil, ErrNotFound
	}
	b, err := os.ReadFile(s.metaPath(id))
	if errors.Is(err, os.ErrNotExist) {
		return nil, ErrNotFound
	}
	if err != nil {
		return nil, err
	}
	var r recipe.Recipe
	if err := json.Unmarshal(b, &r); err != nil {
		return nil, fmt.Errorf("%s/meta.json: %w", id, err)
	}
	// The folder name is the identity; a hand-edited id inside must not
	// make the recipe impossible to address.
	r.ID = id
	return &r, nil
}

// Create writes a new recipe. If the id is taken, a numeric suffix is added
// rather than failing: two "Palacsinta" recipes are normal in a family book.
func (s *Store) Create(r *recipe.Recipe) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	base := r.ID
	for n := 2; ; n++ {
		if _, err := os.Stat(s.Dir(r.ID)); errors.Is(err, os.ErrNotExist) {
			break
		}
		r.ID = fmt.Sprintf("%s-%d", base, n)
		if n > 999 {
			return ErrExists
		}
	}
	now := time.Now().UTC().Truncate(time.Second)
	r.Rev, r.Created, r.Updated = 1, now, now
	if err := os.MkdirAll(s.MediaDir(r.ID), 0o755); err != nil {
		return err
	}
	if err := s.writeMain(r.ID); err != nil {
		return err
	}
	return s.writeMeta(r)
}

// Update saves r if r.Rev matches what is on disk. On success r.Rev is bumped.
func (s *Store) Update(r *recipe.Recipe) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	cur, err := s.Load(r.ID)
	if err != nil {
		return err
	}
	if r.Rev != cur.Rev {
		return &ConflictError{Current: cur}
	}
	if err := s.snapshot(cur); err != nil {
		return err
	}
	r.Created = cur.Created
	r.Rev = cur.Rev + 1
	r.Updated = time.Now().UTC().Truncate(time.Second)
	if err := os.MkdirAll(s.MediaDir(r.ID), 0o755); err != nil {
		return err
	}
	if err := s.writeMain(r.ID); err != nil {
		return err
	}
	return s.writeMeta(r)
}

// Delete moves the folder to <data>/trash: a fat-thumbed delete on a phone
// should cost a file move to undo, not the recipe.
func (s *Store) Delete(id string) error {
	s.mu.Lock()
	defer s.mu.Unlock()
	if _, err := s.Load(id); err != nil {
		return err
	}
	dst := filepath.Join(s.Root, "trash", id+"-"+time.Now().UTC().Format("20060102T150405Z"))
	return os.Rename(s.Dir(id), dst)
}

func (s *Store) writeMeta(r *recipe.Recipe) error {
	b, err := json.MarshalIndent(r, "", "  ")
	if err != nil {
		return err
	}
	return WriteFileAtomic(s.metaPath(r.ID), append(b, '\n'))
}

// mainTyp is the per-recipe Typst entry point. It is deliberately a stub: all
// layout lives in the shared template, so restyling every PDF is one edit.
const mainTyp = `// Generated by CookBook. Layout lives in /templates/recipe.typ.
#import "/templates/recipe.typ": recipe
#recipe(json("meta.json"), lang: sys.inputs.at("lang", default: "hu"))
`

func (s *Store) writeMain(id string) error {
	p := filepath.Join(s.Dir(id), "main.typ")
	if b, err := os.ReadFile(p); err == nil && string(b) == mainTyp {
		return nil
	}
	return WriteFileAtomic(p, []byte(mainTyp))
}

// --- history -----------------------------------------------------------------

type Revision struct {
	File    string    `json:"file"`
	Rev     int       `json:"rev"`
	Updated time.Time `json:"updated"`
}

func (s *Store) historyDir(id string) string { return filepath.Join(s.Dir(id), "history") }

func (s *Store) snapshot(cur *recipe.Recipe) error {
	dir := s.historyDir(cur.ID)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	b, err := json.MarshalIndent(cur, "", "  ")
	if err != nil {
		return err
	}
	name := fmt.Sprintf("%s-rev%d.json", cur.Updated.UTC().Format("20060102T150405Z"), cur.Rev)
	if err := WriteFileAtomic(filepath.Join(dir, name), b); err != nil {
		return err
	}
	// Prune to the newest historyKeep. Names sort chronologically.
	entries, _ := os.ReadDir(dir)
	var names []string
	for _, e := range entries {
		if strings.HasSuffix(e.Name(), ".json") {
			names = append(names, e.Name())
		}
	}
	sort.Strings(names)
	for len(names) > historyKeep {
		os.Remove(filepath.Join(dir, names[0]))
		names = names[1:]
	}
	return nil
}

func (s *Store) History(id string) ([]Revision, error) {
	if _, err := s.Load(id); err != nil {
		return nil, err
	}
	entries, _ := os.ReadDir(s.historyDir(id))
	out := []Revision{}
	for _, e := range entries {
		if !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		b, err := os.ReadFile(filepath.Join(s.historyDir(id), e.Name()))
		if err != nil {
			continue
		}
		var r recipe.Recipe
		if json.Unmarshal(b, &r) != nil {
			continue
		}
		out = append(out, Revision{File: e.Name(), Rev: r.Rev, Updated: r.Updated})
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Rev > out[j].Rev })
	return out, nil
}

func (s *Store) HistoryFile(id, file string) ([]byte, error) {
	if !recipe.ValidID(id) || file != filepath.Base(file) || !strings.HasSuffix(file, ".json") {
		return nil, ErrNotFound
	}
	b, err := os.ReadFile(filepath.Join(s.historyDir(id), file))
	if errors.Is(err, os.ErrNotExist) {
		return nil, ErrNotFound
	}
	return b, err
}

// --- media -------------------------------------------------------------------

// MediaPath returns the path of a media file, or ErrNotFound for anything that
// is not a plain media name (no traversal).
func (s *Store) MediaPath(id, name string) (string, error) {
	if !recipe.ValidID(id) || !recipe.ValidMediaName(name) {
		return "", ErrNotFound
	}
	return filepath.Join(s.MediaDir(id), name), nil
}

func (s *Store) SaveMedia(id, name string, data []byte) error {
	if _, err := s.Load(id); err != nil {
		return err
	}
	p, err := s.MediaPath(id, name)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(s.MediaDir(id), 0o755); err != nil {
		return err
	}
	return WriteFileAtomic(p, data)
}

func (s *Store) DeleteMedia(id, name string) error {
	p, err := s.MediaPath(id, name)
	if err != nil {
		return err
	}
	if err := os.Remove(p); errors.Is(err, os.ErrNotExist) {
		return ErrNotFound
	} else if err != nil {
		return err
	}
	if recipe.IsVideo(name) {
		os.Remove(filepath.Join(s.MediaDir(id), recipe.PosterName(name)))
	}
	return nil
}

// MediaTemp creates a temporary file inside the recipe's media folder, so a
// finished upload can be renamed into place (same filesystem, atomic).
func (s *Store) MediaTemp(id string) (*os.File, error) {
	if _, err := s.Load(id); err != nil {
		return nil, err
	}
	if err := os.MkdirAll(s.MediaDir(id), 0o755); err != nil {
		return nil, err
	}
	return os.CreateTemp(s.MediaDir(id), ".upload-*")
}

// AdoptMedia moves a finished temp file into place under name.
func (s *Store) AdoptMedia(id, name, tmp string) error {
	p, err := s.MediaPath(id, name)
	if err != nil {
		return err
	}
	return os.Rename(tmp, p)
}

func (s *Store) ListMedia(id string) ([]string, error) {
	entries, err := os.ReadDir(s.MediaDir(id))
	if errors.Is(err, os.ErrNotExist) {
		return []string{}, nil
	}
	if err != nil {
		return nil, err
	}
	out := []string{}
	for _, e := range entries {
		if recipe.ValidMediaName(e.Name()) {
			out = append(out, e.Name())
		}
	}
	return out, nil
}

// WriteFileAtomic writes via a temp file and rename, so a crash or power cut on
// the laptop never leaves a half-written meta.json. os.Rename replaces the
// target on Windows too (MoveFileEx with REPLACE_EXISTING).
func WriteFileAtomic(path string, data []byte) error {
	tmp, err := os.CreateTemp(filepath.Dir(path), ".tmp-*")
	if err != nil {
		return err
	}
	name := tmp.Name()
	_, werr := tmp.Write(data)
	serr := tmp.Sync()
	cerr := tmp.Close()
	if err := errors.Join(werr, serr, cerr); err != nil {
		os.Remove(name)
		return err
	}
	if err := os.Rename(name, path); err != nil {
		os.Remove(name)
		return err
	}
	return nil
}
