package dev.cookbook.ui

import androidx.compose.runtime.staticCompositionLocalOf

/**
 * UI text for both languages. The spec's toggle flips content *and* UI
 * together, independent of the phone's system language, so this is app state
 * rather than Android resources.
 */
data class Strings(
	val recipes: String, val discover: String, val grocery: String, val settings: String,
	val search: String, val favorites: String, val all: String, val filters: String,
	val include: String, val exclude: String, val pantry: String, val pantryHint: String,
	val ingredientsHint: String, val noResults: String, val offline: String, val refresh: String,
	val servings: String, val prep: String, val cook: String, val min: String,
	val ingredients: String, val method: String, val notes: String, val optional: String,
	val cookMode: String, val addToList: String, val added: String, val edit: String, val pdf: String,
	val share: String, val delete: String, val deleteConfirm: String, val cancel: String, val ok: String,
	val step: String, val of: String, val next: String, val prev: String, val done: String,
	val timers: String, val pause: String, val resume: String, val dismiss: String,
	val pass: String, val open: String, val endOfStack: String, val startOver: String,
	val listEmpty: String, val addItem: String, val clearDone: String, val clearAll: String,
	val fromRecipes: String, val queued: String, val remove: String,
	val server: String, val serverHint: String, val token: String, val tokenHint: String,
	val test: String, val connected: String, val language: String, val units: String,
	val metric: String, val imperial: String, val about: String, val save: String, val saved: String,
	val newRecipe: String, val title: String, val description: String, val category: String,
	val tags: String, val tagsHint: String, val qty: String, val unit: String, val name: String,
	val group: String, val note: String, val addIngredient: String, val addStep: String,
	val insertIngredient: String, val insertTimer: String, val minutes: String, val photo: String,
	val heroPhoto: String, val autoTranslate: String, val translating: String,
	val translated: (Int, Int) -> String, val conflict: String, val overwrite: String, val reload: String,
	val invalid: String, val editing: String, val missing: String, val canCook: String,
	val setupFirst: String, val noPdf: String, val loading: String, val unsaved: String, val discard: String,
	val moveUp: String, val moveDown: String, val temperature: String, val allCategories: String,
	val pairHint: String, val notTranslated: String, val translateNow: String,
	val importWeb: String, val recipeLink: String, val importing: String, val imported: String,
	val alreadyInBook: String, val methods: String, val autoImport: String, val lastRun: String,
	val nextRun: String, val runNow: String, val running: String, val never: String, val off: String,
	val otherTags: String, val importHint: String,
	val video: String, val watchVideo: String, val videoLink: String, val videoTooLarge: String,
	val uploadingVideo: String,
)

val HU = Strings(
	recipes = "Receptek", discover = "Felfedezés", grocery = "Bevásárlás", settings = "Beállítások",
	search = "Keresés…", favorites = "Kedvencek", all = "Mind", filters = "Szűrők",
	include = "Tartalmazza", exclude = "Ne tartalmazza", pantry = "Mi van itthon?",
	pantryHint = "pl. tojás, liszt, sajt", ingredientsHint = "vesszővel elválasztva",
	noResults = "Nincs találat", offline = "Offline – mentett adatok", refresh = "Frissítés",
	servings = "adag", prep = "Előkészítés", cook = "Főzés", min = "perc",
	ingredients = "Hozzávalók", method = "Elkészítés", notes = "Megjegyzés", optional = "opcionális",
	cookMode = "Főzés mód", addToList = "Bevásárlólistára", added = "Hozzáadva a listához",
	edit = "Szerkesztés", pdf = "PDF", share = "Megosztás", delete = "Törlés",
	deleteConfirm = "Biztosan törlöd? (A szerveren a kukába kerül.)", cancel = "Mégse", ok = "OK",
	step = "Lépés", of = "/", next = "Tovább", prev = "Vissza", done = "Kész",
	timers = "Időzítők", pause = "Szünet", resume = "Folytat", dismiss = "Bezár",
	pass = "Kihagy", open = "Megnyit", endOfStack = "Elfogytak a receptek", startOver = "Újrakezd",
	listEmpty = "A lista üres. Adj hozzá receptet vagy tételt.", addItem = "Tétel hozzáadása…",
	clearDone = "Kipipáltak törlése", clearAll = "Lista ürítése", fromRecipes = "Receptekből",
	queued = "offline módosítás vár küldésre", remove = "Eltávolítás",
	server = "Szerver", serverHint = "Tailscale IP vagy név, pl. 100.64.0.10", token = "Token",
	tokenHint = "a szerver token fájljából", test = "Kapcsolat tesztelése", connected = "Kapcsolódva",
	language = "Nyelv", units = "Mértékegységek", metric = "Metrikus", imperial = "Angolszász",
	about = "Névjegy", save = "Mentés", saved = "Mentve",
	newRecipe = "Új recept", title = "Cím", description = "Leírás", category = "Kategória",
	tags = "Címkék", tagsHint = "vesszővel elválasztva", qty = "Menny.", unit = "Egység", name = "Név",
	group = "Csoport (pl. Tészta)", note = "Megjegyzés (pl. apróra vágva)",
	addIngredient = "Hozzávaló hozzáadása", addStep = "Lépés hozzáadása",
	insertIngredient = "Hozzávaló beszúrása", insertTimer = "Időzítő beszúrása", minutes = "perc",
	photo = "Fotó", heroPhoto = "Borítókép", autoTranslate = "Automatikus fordítás",
	translating = "Fordítás…",
	translated = { f, r -> "$f mező lefordítva" + if (r > 0) ", $r elutasítva (sérült változók)" else "" },
	conflict = "Valaki közben módosította ezt a receptet.", overwrite = "Felülírás", reload = "Újratöltés",
	invalid = "A recept nem érvényes", editing = "Szerkesztett nyelv", missing = "Hiányzik",
	canCook = "Mind megvan!", setupFirst = "Előbb add meg a szervert a Beállításokban.",
	noPdf = "A PDF nem érhető el", loading = "Betöltés…", unsaved = "Elveted a módosításokat?",
	discard = "Elvetés", moveUp = "Fel", moveDown = "Le", temperature = "Hőfok",
	allCategories = "Minden kategória",
	notTranslated = "Ez a recept még nincs meg magyarul.", translateNow = "Fordítás",
	importWeb = "Importálás webről", recipeLink = "Recept linkje", importing = "Importálás…",
	imported = "Importálva", alreadyInBook = "Ez a recept már benne van a könyvben.",
	methods = "Elkészítés módja", autoImport = "Automatikus import", lastRun = "Utolsó futás",
	nextRun = "Következő", runNow = "Futtatás most", running = "Fut…", never = "még nem futott",
	off = "kikapcsolva", otherTags = "További címkék",
	video = "Videó", watchVideo = "Videó megnézése", videoLink = "Videó link (opcionális, pl. YouTube)",
	videoTooLarge = "A videó túl nagy (legfeljebb 300 MB).", uploadingVideo = "Videó feltöltése…",
	importHint = "Bármely receptoldal linkje, pl. nosalty.hu, sobors.hu, bbcgoodfood.com. Böngészőből a Megosztás → CookBook is működik.",
	pairHint = "Egyszerűbb: a szerver gépén nyisd meg a http://localhost:8738/pair oldalt, és olvasd be a QR-kódot a telefon kamerájával.",
)

val EN = Strings(
	recipes = "Recipes", discover = "Discover", grocery = "Grocery", settings = "Settings",
	search = "Search…", favorites = "Favorites", all = "All", filters = "Filters",
	include = "Must include", exclude = "Exclude", pantry = "What do I have?",
	pantryHint = "e.g. egg, flour, cheese", ingredientsHint = "comma separated",
	noResults = "No results", offline = "Offline – showing saved data", refresh = "Refresh",
	servings = "servings", prep = "Prep", cook = "Cook", min = "min",
	ingredients = "Ingredients", method = "Method", notes = "Notes", optional = "optional",
	cookMode = "Cook mode", addToList = "Add to list", added = "Added to the grocery list",
	edit = "Edit", pdf = "PDF", share = "Share", delete = "Delete",
	deleteConfirm = "Delete this recipe? (It goes to the server's trash.)", cancel = "Cancel", ok = "OK",
	step = "Step", of = "/", next = "Next", prev = "Back", done = "Done",
	timers = "Timers", pause = "Pause", resume = "Resume", dismiss = "Dismiss",
	pass = "Pass", open = "Open", endOfStack = "No more recipes", startOver = "Start over",
	listEmpty = "The list is empty. Add a recipe or an item.", addItem = "Add an item…",
	clearDone = "Clear checked", clearAll = "Clear list", fromRecipes = "From recipes",
	queued = "offline changes waiting to sync", remove = "Remove",
	server = "Server", serverHint = "Tailscale IP or name, e.g. 100.64.0.10", token = "Token",
	tokenHint = "from the server's token file", test = "Test connection", connected = "Connected",
	language = "Language", units = "Units", metric = "Metric", imperial = "Imperial",
	about = "About", save = "Save", saved = "Saved",
	newRecipe = "New recipe", title = "Title", description = "Description", category = "Category",
	tags = "Tags", tagsHint = "comma separated", qty = "Qty", unit = "Unit", name = "Name",
	group = "Group (e.g. Dough)", note = "Note (e.g. finely chopped)",
	addIngredient = "Add ingredient", addStep = "Add step",
	insertIngredient = "Insert ingredient", insertTimer = "Insert timer", minutes = "minutes",
	photo = "Photo", heroPhoto = "Cover photo", autoTranslate = "Auto-translate",
	translating = "Translating…",
	translated = { f, r -> "$f fields translated" + if (r > 0) ", $r rejected (broken variables)" else "" },
	conflict = "Someone changed this recipe in the meantime.", overwrite = "Overwrite", reload = "Reload",
	invalid = "The recipe is not valid", editing = "Editing language", missing = "Missing",
	canCook = "You have everything!", setupFirst = "Set up the server in Settings first.",
	noPdf = "PDF not available", loading = "Loading…", unsaved = "Discard your changes?",
	discard = "Discard", moveUp = "Up", moveDown = "Down", temperature = "Temperature",
	allCategories = "All categories",
	notTranslated = "This recipe is not in English yet.", translateNow = "Translate",
	importWeb = "Import from web", recipeLink = "Recipe link", importing = "Importing…",
	imported = "Imported", alreadyInBook = "This recipe is already in the book.",
	methods = "Cooking method", autoImport = "Automatic import", lastRun = "Last run",
	nextRun = "Next", runNow = "Run now", running = "Running…", never = "not run yet",
	off = "off", otherTags = "More tags",
	video = "Video", watchVideo = "Watch video", videoLink = "Video link (optional, e.g. YouTube)",
	videoTooLarge = "The video is too large (300 MB max).", uploadingVideo = "Uploading video…",
	importHint = "A link to any recipe page, e.g. nosalty.hu, sobors.hu, bbcgoodfood.com. Share → CookBook from the browser works too.",
	pairHint = "Easier: on the server machine open http://localhost:8738/pair and scan the QR code with the phone camera.",
)

fun stringsFor(lang: String) = if (lang == "en") EN else HU

val LocalStrings = staticCompositionLocalOf { HU }
