package dev.cookbook.logic

import dev.cookbook.data.AisleKeyword
import dev.cookbook.data.Category
import dev.cookbook.data.GroceryOp
import dev.cookbook.data.GroceryState
import dev.cookbook.data.GroceryView
import dev.cookbook.data.Recipe
import dev.cookbook.data.UnitDef
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The phone must build the same grocery list as the server. The fixture is
 * generated by server/internal/grocery/parity_test.go from the server's own
 * output; if this fails, Grocery.kt and grocery.go have drifted apart.
 */
class GroceryParityTest {
	@Serializable
	private data class Fixture(
		val recipes: List<Recipe>,
		val units: List<UnitDef>,
		val aisles: List<Category>,
		@SerialName("aisle_keywords") val keywords: List<AisleKeyword>,
		val state: GroceryState,
		val expected: GroceryView,
	)

	private val json = Json { ignoreUnknownKeys = true; coerceInputValues = true; explicitNulls = false }

	private val fx: Fixture = json.decodeFromString(
		javaClass.classLoader!!.getResource("grocery_parity.json")!!.readText(),
	)

	private fun aggregate(st: GroceryState) = Grocery.aggregate(
		st, fx.recipes.associateBy { it.id }, fx.units.associateBy { it.id }, fx.aisles, Grocery.guesser(fx.keywords),
	)

	@Test fun sameListAsServer() {
		val got = aggregate(fx.state)
		assertEquals(fx.expected.sections.map { it.category }, got.sections.map { it.category })
		for ((want, have) in fx.expected.sections.zip(got.sections)) {
			assertEquals(want.lines.map { it.key }, have.lines.map { it.key })
			for ((w, h) in want.lines.zip(have.lines)) {
				assertEquals(w.key, w.qty, h.qty)
				assertEquals(w.key, w.unitId, h.unitId)
				assertEquals(w.key, w.unit.orEmpty(), h.unit.orEmpty())
				assertEquals(w.key, w.category, h.category)
				assertEquals(w.key, w.checked, h.checked)
				assertEquals(w.key, w.sources, h.sources)
				assertEquals(w.key, w.name, h.name)
			}
			assertEquals(want.static.map { it.id }, have.static.map { it.id })
		}
		assertEquals(fx.expected.recipes.map { it.id to it.missing }, got.recipes.map { it.id to it.missing })
	}

	@Test fun offlineOpsApplyLikeTheServer() {
		val guess = Grocery.guesser(fx.keywords)
		var st = GroceryState()
		listOf(
			GroceryOp("add_recipe", id = "a", servings = 4.0),
			GroceryOp("add_recipe", id = "a", servings = 8.0), // updates, no duplicate
			GroceryOp("add_static", id = "p-1", text = "Kenyér"),
			GroceryOp("add_static", id = "p-1", text = "Kenyér"), // replay is harmless
			GroceryOp("add_static", id = "p-2", text = "Szemeteszsák"),
			GroceryOp("check", key = "static:p-1", checked = true),
			GroceryOp("check", key = "tojas|unit:pc", checked = true),
		).forEach { st = Grocery.apply(st, it, guess) }
		assertEquals(listOf(8.0), st.recipes.map { it.servings })
		assertEquals(listOf("bakery", "household"), st.static.map { it.category })
		assertTrue(st.static[0].checked)
		assertEquals(listOf("tojas|unit:pc"), st.checked)

		st = Grocery.apply(st, GroceryOp("clear_done"), guess)
		assertEquals(listOf("p-2"), st.static.map { it.id })
		assertTrue(st.checked.isEmpty())

		// And the list is computed without any server.
		val v = aggregate(st)
		assertTrue(v.sections.any { s -> s.lines.any { it.key == "tojas|unit:pc" } })
	}
}
